### ISSUE TITLE
Export problem

### ISSUE THREAD

**Issue by vivindeena** [yas-sim/openvino-llm-minimal-code#1]
Hey, 

thanks for this, but on my system when i try to run the model i get this error, do you have any solutions to this.

```
(venv) PS D:\intel\LLM\openvino-llm-minimal-code> optimum-cli export openvino -m intel/neural-chat-7b-v3 --weight-format int4_sym_g64 neural-chat-7b-v3/INTtoken4
Framework not specified. Using pt to export to ONNX.
```

**Comment by yas-sim** [comment]
This message (Framework not specified. Using pt to export to ONNX.) is shown on my system, too, but it's not an error. Is it returned to the command prompt and didn't download anything after the message?

**Comment by yas-sim** [comment]
Any update? Can I close this issue?

**Comment by yas-sim** [comment]
I will close this issue. Thanks.
